{% set version = "0.1.0a4" %}
{% set min_python = "python >=3.10" %}

package:
  name: pyodide-lock-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyodide-lock/pyodide_lock-{{ version }}.tar.gz
  sha256: d24d98d1e72c38faa6f573e559e84541fb8d3d38bf1b3da05da65a1d4e027d49

build:
  noarch: python
  number: 0

requirements:
  host:
    - {{ min_python }}
  run:
    - {{ min_python }}

outputs:
  - name: pyodide-lock
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - {{ min_python }}
        - hatch-vcs
        - hatchling
        - pip
      run:
        - {{ min_python }}
        - pydantic >=1.10.2,<2
    test:
      imports:
        - pyodide_lock
      commands:
        - pip check
      requires:
        - pip

  - name: pyodide-lock-with-wheel
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("pyodide-lock", exact=True) }}
        - packaging
        - pkginfo
    test:
      imports:
        - pyodide_lock
      commands:
        - pip check
      requires:
        - pip

  - name: pyodide-lock-with-cli
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("pyodide-lock", exact=True) }}
        - typer
    test:
      imports:
        - pyodide_lock.cli
      commands:
        - pip check
      requires:
        - pip

  - name: pyodide-lock-with-all
    build:
      noarch: python
    requirements:
      host:
        - {{ min_python }}
      run:
        - {{ min_python }}
        - {{ pin_subpackage("pyodide-lock", exact=True) }}
        - {{ pin_subpackage("pyodide-lock-with-cli", exact=True) }}
        - {{ pin_subpackage("pyodide-lock-with-wheel", exact=True) }}
    test:
      source_files:
        - tests
      imports:
        - pyodide_lock
        - pyodide_lock.cli
      commands:
        - pip check
        - coverage run --source=pyodide_lock --branch -m pytest -vv --color=yes
        - coverage report --show-missing --skip-covered --fail-under=92
      requires:
        - coverage
        - pip
        - pytest
        - python-build

about:
  home: https://github.com/pyodide/pyodide-lock
  summary: Tooling to manage the `pyodide-lock.json` file
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  feedstock-name: pyodide-lock
  recipe-maintainers:
    - bollwyvl
