{% set version = "0.1.0a6" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: pyodide-lock-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyodide-lock/pyodide_lock-{{ version }}.tar.gz
  sha256: a4584e0e31270828b97587c1831e7aaa330f3318600392733537184ba511d279

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.10
  run:
    - python >=3.10

outputs:
  - name: pyodide-lock
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - hatch-vcs
        - hatchling
        - pip
        - python >=3.10
      run:
        - pydantic >=2
        - python >=3.10
    test:
      imports:
        - pyodide_lock
      commands:
        - pip check
      requires:
        - pip

  - name: pyodide-lock-with-wheel
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pyodide-lock", exact=True) }}
        - packaging
        - pkginfo
    test:
      imports:
        - pyodide_lock
      commands:
        - pip check
      requires:
        - pip

  - name: pyodide-lock-with-cli
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pyodide-lock", exact=True) }}
        - typer
    test:
      imports:
        - pyodide_lock.cli
      commands:
        - pip check
      requires:
        - pip

  - name: pyodide-lock-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pyodide-lock", exact=True) }}
        - {{ pin_subpackage("pyodide-lock-with-cli", exact=True) }}
        - {{ pin_subpackage("pyodide-lock-with-wheel", exact=True) }}
    test:
      source_files:
        - tests
      imports:
        - pyodide_lock
        - pyodide_lock.cli
      commands:
        - pip check
        - coverage run --source=pyodide_lock --branch -m pytest -vv --color=yes
        - coverage report --show-missing --skip-covered --fail-under=92
      requires:
        - coverage
        - pip
        - pytest
        - python-build

about:
  home: https://github.com/pyodide/pyodide-lock
  summary: Tooling to manage the `pyodide-lock.json` file
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  feedstock-name: pyodide-lock
  recipe-maintainers:
    - bollwyvl
