{% set version = "0.1.0a4" %}

package:
  name: pyodide-lock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyodide-lock/pyodide_lock-{{ version }}.tar.gz
  sha256: d24d98d1e72c38faa6f573e559e84541fb8d3d38bf1b3da05da65a1d4e027d49

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.10
    - pydantic

test:
  source_files:
    - tests
  imports:
    - pyodide_lock
  commands:
    - pip check
    - pytest -vv --cov=pyodide_lock --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=81
  requires:
    - pip
    - pytest-cov

about:
  home: https://github.com/pyodide/pyodide-lock
  summary: Tooling to manage the `pyodide-lock.json` file
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
