{% set version = "0.1.0a8" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: pyodide-lock
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyodide-lock/pyodide_lock-{{ version }}.tar.gz
  sha256: 9ad5af230d30078aacc1d8055fae6b2273b5a882786eb30cc0b446d69f3af49e

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - pydantic >=2
    - python >={{ python_min }}

test:
  imports:
    - pyodide_lock
  commands:
    - pip check
  requires:
    - pip


outputs:
  - name: pyodide-lock

  - name: pyodide-lock-with-wheel
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pyodide-lock", exact=True) }}
        - packaging
        - pkginfo
    test:
      imports:
        - pyodide_lock
      commands:
        - pip check
      requires:
        - pip

  - name: pyodide-lock-with-cli
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pyodide-lock", exact=True) }}
        - typer
    test:
      imports:
        - pyodide_lock.cli
      commands:
        - pip check
      requires:
        - pip

  - name: pyodide-lock-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("pyodide-lock", exact=True) }}
        - {{ pin_subpackage("pyodide-lock-with-cli", exact=True) }}
        - {{ pin_subpackage("pyodide-lock-with-wheel", exact=True) }}
    test:
      source_files:
        - tests
      requires:
        - coverage
        - pip
        - pytest
        - python-build
      imports:
        - pyodide_lock
        - pyodide_lock.cli
      commands:
        - pip check
        - coverage run --source=pyodide_lock --branch -m pytest -vv --color=yes
        - coverage report --show-missing --skip-covered --fail-under=92

about:
  home: https://github.com/pyodide/pyodide-lock
  summary: Tooling to manage the `pyodide-lock.json` file
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  feedstock-name: pyodide-lock
  recipe-maintainers:
    - bollwyvl
